[package]
name = "ccomp-template"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["ringas (https://github.com/ringass)"]
license = "MIT"
description = "A Typst slide template for Circuitando Sonhos, the robotics project from UNESP Bauru."
repository = "https://github.com/ringass/circuitypst"
keywords = ["circuitando sonhos", "slides", "presentation", "unesp"]
categories = ["presentation"]
compiler = "0.13.0"
[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "assets/lesson1.png"
